"use client";

import React, { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';

interface MathRendererProps {
    content: string;
}

const preprocessLaTeX = (text: string) => {
    if (!text) return "";
    let processed = text;
    // Replace standard LaTeX delimiters
    processed = processed.replace(/\\\[([\s\S]*?)\\\]/g, (_, math) => `\n\n$$\n${math}\n$$\n\n`);
    processed = processed.replace(/\\\(([\s\S]*?)\\\)/g, (_, math) => `$${math}$`);
    
    // Ensure environments like \begin{align*} are wrapped in $$ if they aren't already.
    // We clean up existing $$ surrounding the block first to avoid $$$$...
    processed = processed.replace(/\$\$\s*\\begin\{(align|aligned|equation)\*?\}([\s\S]*?)\\end\{\1\*?\}\s*\$\$/g, (_, env, inner) => {
        return `\n\n$$\n\\begin{aligned}${inner}\\end{aligned}\n$$\n\n`;
    });
    // Then wrap bare environments
    processed = processed.replace(/(?<!\$\$)\s*\\begin\{(align|aligned|equation)\*?\}([\s\S]*?)\\end\{\1\*?\}\s*(?!\$\$)/g, (_, env, inner) => {
        return `\n\n$$\n\\begin{aligned}${inner}\\end{aligned}\n$$\n\n`;
    });
    
    // Heuristic capture for bare bracket block equations e.g. [ \Delta = 4 ] often spit out by some models
    processed = processed.replace(/\[\s*([\s\S]*?)\s*\]/g, (match, inner) => {
        const hasMath = inner.includes('\\') || inner.includes('^') || inner.includes('=') || inner.match(/[0-9][-+*\/]/) || inner.includes('_');
        const isCommonWord = /^[a-zA-Z\s]+$/.test(inner); // Pure words shouldn't be math
        if (hasMath && !isCommonWord) {
            return `\n\n$$\n${inner}\n$$\n\n`;
        }
        return match;
    });

    // Fix $ \n ... \n $ incorrectly generated by LLM for block equations (converting to $$)
    // Allow for \r\n (CRLF) and multiple newlines
    processed = processed.replace(/(?<!\$)\$[ \t\r]*\n([\s\S]*?)\n[ \t\r]*\$(?!\$)/g, (match, inner) => {
        if (inner.includes('$')) return match; // Abort if we crossed into another math block
        return `\n\n$$\n${inner.trim()}\n$$\n\n`;
    });

    // Safely force block-math `$$` to be padded with newlines, forcing remark-math to parse them as display blocks 
    // rather than inline nodes (which otherwise causes UI elements to render side-by-side). Using '$$$$' safely escapes to '$$'.
    processed = processed.replace(/(?<!\$)\$\$(?!\$)/g, '\n\n$$$$\n\n');

    // The previous transforms might generate excessive newlines, collapse them safely:
    processed = processed.replace(/\n{3,}/g, '\n\n');

    return processed;
};

const MathRenderer: React.FC<MathRendererProps> = ({ content }) => {
    const processedContent = useMemo(() => preprocessLaTeX(content), [content]);

    return (
        <div className="math-content prose dark:prose-invert max-w-none">
            <ReactMarkdown
                remarkPlugins={[remarkMath]}
                rehypePlugins={[[rehypeKatex, { strict: false, throwOnError: false }]]}
                components={{
                    p: ({ node, ...props }) => <p className="mb-2" {...props} />,
                    // Add some base styling for headings so Markdown actually renders nicely
                    h3: ({ node, ...props }) => <h3 className="text-lg font-bold mt-4 mb-2" {...props} />,
                    h4: ({ node, ...props }) => <h4 className="text-base font-bold mt-3 mb-1" {...props} />
                }}
            >
                {processedContent}
            </ReactMarkdown>
        </div>
    );
};

export default MathRenderer;
